language: cpp

compiler: gcc

os: linux

before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -qq update
        - wget http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2
        - tar --bzip2 -xf boost_1_55_0.tar.bz2
        - cd boost_1_55_0
        - ./bootstrap.sh --help
        - sudo ./bootstrap.sh --with-libraries="atomic"
        # Way too much output, so just display the last 50 lines.
        - sudo ./b2 install | tail -n 50
        - cd ..

install:
        - sudo apt-get install -y libfftw3-dev libjemalloc-dev
        - sudo apt-get install -qq g++-4.8

script:
        - make --jobs=3 --keep-going
        - make clean
